version: '3'
services:
  node:
    image: node:21-alpine3.18
    container_name: node
    volumes:
      - .:/app
    tty: true
    ports:
      - 8080:8080
      - 3001:3001
    working_dir: /app
    command: sh -c "npm install && npm run dev"
