[build]
  publish = "_site"
  command = "yarn build"

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=31536000;"
X-Content-Type-Options = "nosniff;"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"